title: Eclipse JNoSQL™
lang: en
description: Eclipse JNoSQL™ is a Java framework that helps developers create enterprise-grade applications using Java and NoSQL technologies while reducing coupling to the underlying NoSQL database.

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
